# Generated by Django 3.2.16 on 2022-11-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('add_orders', 'Can Add Orders'),)},
        ),
    ]
